### ISSUE TITLE
User auth security for production usage

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/elixir_plug_server_timing#3]
The Ruby version of our server timing provides a couple methods for toggling the generation of the server timing response headers. This is needed when running in production to prevent exposing the data to everyone.

[See the Ruby README](https://github.com/scoutapp/ruby_server_timing#security). The logic is in the [`Auth` Class](https://github.com/scoutapp/ruby_server_timing/blob/master/lib/server_timing/auth.rb).

It'd be great to have these functions in the Elixir package.

**Comment by mitchellhenke** [comment]
Closed in #4
